import XCTest

@testable import CaptureCore

/// Decoding coverage for the `bob-contract` completion shape:
/// `task_block_id` context, the additive top-level `block_id` object, and
/// the additive candidate `line`/`pomodoro` keys.
///
/// Fixtures (`Tests/Fixtures/block-id-*.json`) were generated by a `bob`
/// built from bob-cli master (after the `bob-contract` phase) against a
/// temp vault holding `notes.md` (two headings; identified Ready, In
/// Progress, Next, and Blocked tasks; a nested task; a done task with an
/// ID; a non-task `^anchor`), a day file with one `BUGS` Pomodoro holding
/// the `notes#^tool` Task Link, and `#task` global-filter settings:
///
///   bob capture-complete -b VAULT -c 7 -f json -- '@notes:'
///   bob capture-complete -b VAULT -c 10 -f json -- '@notes:rea'
///   bob capture-complete -b VAULT -c 22 -f json -- 'Fix flaky test @notes^'
///   bob capture-complete -b VAULT -c 22 -f json -- 'Fix flaky test @notes:'
///   bob capture-complete -b VAULT -c 8 -f json -- '@notes^x+'
///   bob capture-complete -b VAULT -c 9 -f json -- '@missing:'
final class BlockIDDecodingTests: XCTestCase {
    private func fixtureResponse(_ name: String) throws -> CaptureCompletionResponse {
        let fixtures = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures", isDirectory: true)
        let text = try String(
            contentsOf: fixtures.appendingPathComponent(name),
            encoding: .utf8
        )
        return try JSONDecoder().decode(CaptureCompletionResponse.self, from: Data(text.utf8))
    }

    // MARK: - Link snapshot

    func testLinkFullResponseDecodesIntentCandidatesAndUsedIDs() throws {
        let response = try fixtureResponse("block-id-link-full.json")

        XCTAssertEqual(CaptureCompletionContext(rawContext: response.context), .pomodoroBlockID)
        XCTAssertEqual(response.replacement, CaptureRange(start: 7, end: 7))
        XCTAssertEqual(response.candidates.count, 6)

        let field = try XCTUnwrap(response.blockID)
        XCTAssertEqual(field.route, "notes")
        XCTAssertEqual(field.relativeTarget, "notes.md")
        XCTAssertTrue(field.noteExists)
        XCTAssertEqual(field.marker, ":")
        XCTAssertEqual(field.markerRange, CaptureRange(start: 0, end: 7))
        XCTAssertEqual(field.intent, .link)
        XCTAssertEqual(field.body, "")
        XCTAssertEqual(field.allowedCharacter, "[A-Za-z0-9_-]")
        XCTAssertEqual(field.allowedDescription, "A-Z, a-z, 0-9, '_' or '-'")
        XCTAssertEqual(field.suggestions, [])
        XCTAssertEqual(field.used.map { $0.id }, [
            "anchor", "recovery-plan", "fix-flaky", "release-v18",
            "vendor-key", "nested-follow", "tool", "ready",
        ])
    }

    func testLinkUsedEntriesDistinguishTasksAnchorsAndDone() throws {
        let field = try XCTUnwrap(try fixtureResponse("block-id-link-full.json").blockID)

        let anchor = try XCTUnwrap(field.used.first { $0.id == "anchor" })
        XCTAssertFalse(anchor.isTask)
        XCTAssertEqual(anchor.line, 3)
        XCTAssertNil(anchor.statusSymbol)
        XCTAssertNil(anchor.statusName)
        XCTAssertEqual(anchor.text, "Some paragraph")

        let tool = try XCTUnwrap(field.used.first { $0.id == "tool" })
        XCTAssertTrue(tool.isTask)
        XCTAssertEqual(tool.line, 18)
        XCTAssertEqual(tool.statusSymbol, " ")
        XCTAssertEqual(tool.statusName, "Ready")
        XCTAssertEqual(tool.text, "Add tool command to wrap calls")

        let ready = try XCTUnwrap(field.used.first { $0.id == "ready" })
        XCTAssertTrue(ready.isTask)
        XCTAssertEqual(ready.statusSymbol, "x")
        XCTAssertEqual(ready.statusName, "Done")
    }

    func testLinkCandidatesCarryLinePomodoroSectionAndDepth() throws {
        let response = try fixtureResponse("block-id-link-full.json")

        let tool = try XCTUnwrap(response.candidates.first { $0.blockID == "tool" })
        XCTAssertEqual(tool.replacement, "tool")
        XCTAssertEqual(tool.route, "notes")
        XCTAssertEqual(tool.line, 18)
        XCTAssertEqual(tool.section, "Tasks")
        XCTAssertEqual(tool.depth, 0)
        let pomodoro = try XCTUnwrap(tool.pomodoro)
        XCTAssertEqual(pomodoro.line, 2)
        XCTAssertEqual(pomodoro.name, "BUGS")
        XCTAssertEqual(pomodoro.timeRange, "0905-0930")
        XCTAssertTrue(pomodoro.isCurrent)

        let unqueued = try XCTUnwrap(response.candidates.first { $0.blockID == "fix-flaky" })
        XCTAssertNil(unqueued.pomodoro)
        XCTAssertEqual(unqueued.statusSymbol, "/")
        XCTAssertEqual(unqueued.section, "Next & In Progress")

        let nested = try XCTUnwrap(response.candidates.first { $0.blockID == "nested-follow" })
        XCTAssertEqual(nested.depth, 1)
        XCTAssertEqual(nested.section, "Blocked")
    }

    func testLinkFilteredResponseKeepsCaretReplacement() throws {
        let response = try fixtureResponse("block-id-link-filtered.json")

        XCTAssertEqual(CaptureCompletionContext(rawContext: response.context), .pomodoroBlockID)
        XCTAssertEqual(response.replacement, CaptureRange(start: 7, end: 10))
        XCTAssertEqual(response.candidates.count, 0)
        XCTAssertEqual(try XCTUnwrap(response.blockID).intent, .link)
    }

    // MARK: - New ID snapshots

    func testNewCaretResponseDecodesBodySuggestionsAndCaretGrammar() throws {
        let response = try fixtureResponse("block-id-new-caret.json")

        XCTAssertEqual(CaptureCompletionContext(rawContext: response.context), .taskBlockID)
        XCTAssertEqual(response.replacement, CaptureRange(start: 22, end: 22))
        XCTAssertEqual(response.candidates, [])

        let field = try XCTUnwrap(response.blockID)
        XCTAssertEqual(field.route, "notes")
        XCTAssertEqual(field.marker, "^")
        XCTAssertEqual(field.markerRange, CaptureRange(start: 15, end: 22))
        XCTAssertEqual(field.intent, .new)
        XCTAssertEqual(field.body, "Fix flaky test")
        XCTAssertEqual(field.allowedCharacter, "[A-Za-z0-9-]")
        XCTAssertEqual(field.allowedDescription, "A-Z, a-z, 0-9 or '-'")
        XCTAssertEqual(field.suggestions, ["fix-flaky-test", "flaky-test"])
        XCTAssertEqual(field.used.count, 8)
    }

    func testNewColonResponseUsesColonGrammarAndNewIntent() throws {
        let field = try XCTUnwrap(try fixtureResponse("block-id-new-colon.json").blockID)

        XCTAssertEqual(field.marker, ":")
        XCTAssertEqual(field.intent, .new)
        XCTAssertEqual(field.allowedCharacter, "[A-Za-z0-9_-]")
        XCTAssertEqual(field.body, "Fix flaky test")
        XCTAssertFalse(field.suggestions.isEmpty)
    }

    func testProjectNoteResponseHasEmptyUsedList() throws {
        let response = try fixtureResponse("block-id-project-note.json")

        XCTAssertEqual(CaptureCompletionContext(rawContext: response.context), .taskBlockID)
        let field = try XCTUnwrap(response.blockID)
        XCTAssertEqual(field.intent, .projectNote)
        XCTAssertEqual(field.marker, "^")
        XCTAssertEqual(field.used, [])
    }

    func testMissingNoteResponseIsNotAnError() throws {
        let response = try fixtureResponse("block-id-missing-note.json")

        let field = try XCTUnwrap(response.blockID)
        XCTAssertEqual(field.route, "missing")
        XCTAssertEqual(field.relativeTarget, "missing.md")
        XCTAssertFalse(field.noteExists)
        XCTAssertEqual(field.used, [])
        XCTAssertEqual(field.intent, .link)
    }

    // MARK: - Tolerant decoding

    func testMissingBlockIDDecodesAsNil() throws {
        let response = try JSONDecoder().decode(
            CaptureCompletionResponse.self,
            from: Data(
                """
                {"ok":true,"schema_version":1,"cursor":1,"replacement":{"start":0,"end":1},"context":"route","candidates":[]}
                """.utf8
            )
        )
        XCTAssertNil(response.blockID)
        XCTAssertEqual(CaptureCompletionContext(rawContext: response.context), .route)
    }

    func testEmptyBlockIDObjectDecodesToDocumentedDefaults() throws {
        let field = try JSONDecoder().decode(
            CaptureBlockIDField.self,
            from: Data("{}".utf8)
        )
        XCTAssertEqual(field.route, "")
        XCTAssertEqual(field.relativeTarget, "")
        XCTAssertFalse(field.noteExists)
        XCTAssertEqual(field.marker, "")
        XCTAssertNil(field.markerRange)
        XCTAssertEqual(field.intent, .link)
        XCTAssertEqual(field.body, "")
        XCTAssertEqual(field.allowedCharacter, "")
        XCTAssertEqual(field.allowedDescription, "")
        XCTAssertEqual(field.suggestions, [])
        XCTAssertEqual(field.used, [])
    }

    func testUnknownIntentDecodesToLink() {
        XCTAssertEqual(CaptureBlockIDIntent(wireValue: "link"), .link)
        XCTAssertEqual(CaptureBlockIDIntent(wireValue: "new"), .new)
        XCTAssertEqual(CaptureBlockIDIntent(wireValue: "project_note"), .projectNote)
        XCTAssertEqual(CaptureBlockIDIntent(wireValue: "frob"), .link)
        XCTAssertEqual(CaptureBlockIDIntent(wireValue: nil), .link)
    }

    func testCompletionContextMapsTaskBlockIDAndRejectsUnknown() {
        XCTAssertEqual(
            CaptureCompletionContext(rawContext: "task_block_id"),
            .taskBlockID
        )
        XCTAssertEqual(
            CaptureCompletionContext(rawContext: "pomodoro_block_id"),
            .pomodoroBlockID
        )
        XCTAssertNil(CaptureCompletionContext(rawContext: "block_id"))
        XCTAssertNil(CaptureCompletionContext(rawContext: nil))
    }

    func testCandidatesWithoutLineOrPomodoroDecodeAsNil() throws {
        let candidate = try JSONDecoder().decode(
            CaptureCompletionCandidate.self,
            from: Data(
                """
                {"replacement":"tool","route":"notes","block_id":"tool"}
                """.utf8
            )
        )
        XCTAssertNil(candidate.line)
        XCTAssertNil(candidate.pomodoro)
        XCTAssertEqual(candidate.blockID, "tool")
    }
}
