import XCTest

@testable import CaptureCore

/// Presentation coverage for batch-level `pomodoro_blocks`: captions and
/// glyphs per status, the New/Created badge, rows and depth clamping, the
/// before text, accessibility, and the covers-preview-lines rule.
///
/// Fixtures (`Tests/Fixtures/pomodoro-*-blocks.json`) were generated by a
/// `bob` built from bob-cli master (after the `blocks_tracker` phase) with
/// real (committed, `"dry_run": false`) captures against sandbox vaults:
///
///   adjust/shift/chain (`BOB_NOW="2026-09-30 07:20:00"`, day file
///   `vault/2026/20260930.md` holding `# Day`, `## Pomodoros`, the
///   `CLEANUP 0620-0710` entry with its three Task Links, and the `GTD`
///   placeholder):
///     BOB_DAY_FILE=…/2026/20260930.md bob capture -b vault -f json -- "+5"
///     BOB_DAY_FILE=…/2026/20260930.md bob capture -b vault -f json -- "++1"
///     BOB_DAY_FILE=…/2026/20260930.md bob capture -b vault -f json -- "+2 =x"
///   start (`BOB_NOW="2026-09-28 09:42:00"`, day file `vault/day.md` holding
///   `## Pomodoros`, the `GTD` placeholder with `[[#^gtd]]` and a context
///   line, and a completed `PLAN` entry):
///     BOB_DAY_FILE=…/day.md bob capture -b vault -f json -- "="
///   named start creating its entry (`BOB_NOW="2026-09-30 07:20:00"`, day
///   file `vault/day.md` holding `## Pomodoros`, a completed `CLEANUP`
///   entry, and the `GTD` placeholder):
///     BOB_DAY_FILE=…/day.md bob capture -b vault -f json -- "=#focus"
///   close (the `docs/capture.md` worked example:
///   `BOB_NOW="2026-09-28 09:37:00"`, day file `vault/2026/20260928.md`,
///   plus `bob.md`, `sase.md`, and the obsidian-tasks-plugin settings from
///   `close_worked_vault` in bob-cli's `pomodoro_close` CLI tests):
///     BOB_DAY_FILE=…/2026/20260928.md bob capture -b vault -f json -- "=x"
final class CapturePomodoroBlockPresentationTests: XCTestCase {
    private func blockFixture(_ name: String) throws -> CaptureCommandSuccess {
        let fixtures = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures", isDirectory: true)
        let text = try String(
            contentsOf: fixtures.appendingPathComponent(name),
            encoding: .utf8
        )
        let decoded = try JSONDecoder().decode(
            CaptureCommandResponse.self,
            from: Data(text.utf8)
        )
        guard case .success(let success) = decoded else {
            throw BlockPresentationFixtureError.expectedSuccess
        }
        return success
    }

    private func presentation(
        _ fixture: String,
        blockIndex: Int = 0,
        dryRun: Bool = false
    ) throws -> CapturePomodoroBlockPresentation {
        let success = try blockFixture(fixture)
        return CapturePomodoroBlockPresentation(
            block: success.pomodoroBlocks[blockIndex],
            dryRun: dryRun
        )
    }

    // MARK: - Captions, glyphs, and badges

    func testRunningCaptionAndGlyph() throws {
        let presented = try presentation("pomodoro-adjust-blocks.json", dryRun: true)

        XCTAssertEqual(presented.status, .running)
        XCTAssertEqual(presented.captionText, "Running · line 5")
        XCTAssertEqual(presented.statusSymbolName, "play.circle.fill")
        XCTAssertNil(presented.badgeText)
    }

    func testCompletedCaptionAndGlyph() throws {
        let presented = try presentation("pomodoro-close-blocks.json")

        XCTAssertEqual(presented.status, .completed)
        XCTAssertEqual(presented.captionText, "Completed · line 5")
        XCTAssertEqual(presented.statusSymbolName, "checkmark.circle.fill")
        XCTAssertNil(presented.badgeText)
    }

    func testQueuedCaptionGlyphAndNewBadge() throws {
        let presented = try presentation(
            "pomodoro-close-blocks.json",
            blockIndex: 1,
            dryRun: true
        )

        XCTAssertEqual(presented.status, .queued)
        XCTAssertEqual(presented.captionText, "Queued · line 13")
        XCTAssertEqual(presented.statusSymbolName, "circle.dashed")
        XCTAssertEqual(presented.badgeText, "New")
    }

    func testCreatedBadgeReadsCreatedOnceCommitted() throws {
        let presented = try presentation(
            "pomodoro-close-blocks.json",
            blockIndex: 1,
            dryRun: false
        )

        XCTAssertEqual(presented.badgeText, "Created")
    }

    func testUnknownStatusFallsBackToNeutralCaption() throws {
        let presented = CapturePomodoroBlockPresentation(
            block: CapturePomodoroBlock(
                relativeTarget: "day.md",
                line: 2,
                name: "GTD",
                status: .other
            ),
            dryRun: true
        )

        XCTAssertEqual(presented.captionText, "Pomodoro · line 2")
        XCTAssertEqual(presented.statusSymbolName, "circle.dashed")
    }

    // MARK: - Rows

    func testAdjustRowsStripIndentationAndMarkHeadline() throws {
        let presented = try presentation("pomodoro-adjust-blocks.json", dryRun: true)

        XCTAssertEqual(presented.rows.count, 4)
        let headline = presented.rows[0]
        XCTAssertEqual(headline.content, "- [ ] (**0620-0735** [t:: 75m]) — CLEANUP")
        XCTAssertEqual(headline.depth, 0)
        XCTAssertEqual(headline.change, .changed)
        XCTAssertEqual(
            headline.beforeContent,
            "- [ ] (**0620-0710** [t:: 50m]) — CLEANUP"
        )
        XCTAssertTrue(headline.isHeadline)
        XCTAssertFalse(headline.tokens.isEmpty)

        for child in presented.rows.dropFirst() {
            XCTAssertEqual(child.depth, 1)
            XCTAssertEqual(child.change, .unchanged)
            XCTAssertNil(child.beforeContent)
            XCTAssertFalse(child.isHeadline)
            XCTAssertFalse(child.tokens.isEmpty)
        }
        XCTAssertEqual(
            presented.rows[1].content,
            "- [[sase#^re-launch-failed]]"
        )
    }

    func testDepthClampsToMaxDepth() throws {
        let deep = CapturePomodoroBlockPresentation(
            block: CapturePomodoroBlock(
                relativeTarget: "day.md",
                line: 2,
                lines: [
                    CapturePomodoroBlockLine(text: "\t- deep", depth: 99),
                    CapturePomodoroBlockLine(text: "- top", depth: -3),
                ]
            ),
            dryRun: true
        )

        XCTAssertEqual(deep.rows[0].depth, CapturePomodoroBlockPresentation.maxDepth)
        XCTAssertFalse(deep.rows[0].isHeadline)
        XCTAssertEqual(deep.rows[1].depth, 0)
        XCTAssertTrue(deep.rows[1].isHeadline)
    }

    func testBlankDepthZeroLineIsNotAHeadline() throws {
        let presented = CapturePomodoroBlockPresentation(
            block: CapturePomodoroBlock(
                relativeTarget: "day.md",
                line: 2,
                lines: [CapturePomodoroBlockLine(text: "", depth: 0)]
            ),
            dryRun: true
        )

        XCTAssertFalse(presented.rows[0].isHeadline)
    }

    // MARK: - Accessibility

    func testAccessibilityNamesPomodoroStatusLineAndChanges() throws {
        let presented = try presentation("pomodoro-adjust-blocks.json", dryRun: true)

        XCTAssertTrue(
            presented.accessibilitySummary.hasPrefix("CLEANUP, Running, line 5: ")
        )
        XCTAssertTrue(
            presented.accessibilitySummary.contains(
                "changed from - [ ] (**0620-0710** [t:: 50m]) — CLEANUP"
                    + " to - [ ] (**0620-0735** [t:: 75m]) — CLEANUP"
            )
        )
        XCTAssertTrue(
            presented.accessibilitySummary.contains("- [[sase#^re-launch-failed]]")
        )
    }

    func testAccessibilityAnnouncesCreatedBadgeAndAddedLines() throws {
        let presented = try presentation(
            "pomodoro-close-blocks.json",
            blockIndex: 1,
            dryRun: true
        )

        XCTAssertTrue(
            presented.accessibilitySummary.hasPrefix("CAPTURE, Queued, line 13, New: ")
        )
        XCTAssertTrue(
            presented.accessibilitySummary.contains("added - [ ] () — CAPTURE")
        )
    }

    func testUnblockedSuccessorLineMarksRowAndVoiceOver() throws {
        let success = try blockFixture("pomodoro-close-successors.json")
        let created = try XCTUnwrap(success.pomodoroBlocks.first { $0.created })
        let presented = CapturePomodoroBlockPresentation(block: created, dryRun: true)

        let badge = try XCTUnwrap(
            presented.rows.first { $0.content.contains("[[sase#^relaunch-failed-agents]]") }
        )
        XCTAssertEqual(badge.change, .added)
        XCTAssertTrue(badge.isUnblocked)
        XCTAssertTrue(
            presented.accessibilitySummary.contains(
                "added - [[sase#^relaunch-failed-agents]], unblocked successor"
            )
        )
        // Every other row carries no badge.
        for row in presented.rows where !row.content.contains("[[sase#^relaunch-failed-agents]]") {
            XCTAssertFalse(row.isUnblocked, "unexpected badge on \(row.content)")
        }
    }

    func testAccessibilityFallsBackToUnnamed() throws {
        let presented = CapturePomodoroBlockPresentation(
            block: CapturePomodoroBlock(
                relativeTarget: "day.md",
                line: 4,
                status: .queued,
                lines: [CapturePomodoroBlockLine(text: "- [ ] ()", depth: 0)]
            ),
            dryRun: false
        )

        XCTAssertTrue(presented.accessibilitySummary.hasPrefix("Unnamed, Queued, line 4: "))
    }

    // MARK: - Covers rule

    func testCoversIsTrueForAdjustAndShift() throws {
        for fixture in ["pomodoro-adjust-blocks.json", "pomodoro-shift-blocks.json"] {
            let success = try blockFixture(fixture)
            XCTAssertTrue(
                CapturePomodoroBlockPresentation.covers(success, blocks: success.pomodoroBlocks),
                "\(fixture) should be covered"
            )
        }
    }

    func testCoversIsFalseForPomodoroTaskInARouteNote() throws {
        let decoded = try JSONDecoder().decode(
            CaptureCommandResponse.self,
            from: Data(
                """
                {"ok":true,"dry_run":true,"routed":true,"route":"sase","route_label":"sase.md",
                "relative_target":"sase.md","target":"/tmp/vault/sase.md",
                "text":"Write outline","task_line":"- [*] #task Write outline [created::2026-09-28] ^outline",
                "kind":"pomodoro_task","created":"2026-09-28","scheduled":null,"placement":"inserted",
                "block_id":"outline","day_file":"/tmp/vault/2026/20260928.md","block_link":"[[sase#^outline]]",
                "pomodoro_blocks":[{"relative_target":"2026/20260928.md","line":5,"name":"GTD",
                "time_range":"0900-0925","status":"running","created":false,"roles":["linked"],
                "lines":[{"text":"- [ ] (**0900-0925** [t:: 25m]) — GTD","depth":0,"change":"unchanged"}]}]}
                """.utf8
            )
        )
        guard case .success(let success) = decoded else {
            throw BlockPresentationFixtureError.expectedSuccess
        }

        XCTAssertFalse(
            CapturePomodoroBlockPresentation.covers(success, blocks: success.pomodoroBlocks)
        )
    }

    func testCoversIsFalseWithoutBlocks() throws {
        let success = try blockFixture("pomodoro-close-worked.json")

        XCTAssertEqual(success.pomodoroBlocks, [])
        XCTAssertFalse(
            CapturePomodoroBlockPresentation.covers(success, blocks: success.pomodoroBlocks)
        )
    }

    func testCoversIgnoresRemovedLines() throws {
        let success = try blockFixture("pomodoro-close-blocks.json")
        // The removed `[[bob#^web-capture]]#` line must not satisfy a
        // preview that names only it.
        let removedOnly = CapturePomodoroBlock(
            relativeTarget: "2026/20260928.md",
            line: 5,
            lines: [
                CapturePomodoroBlockLine(
                    text: "\t- [[bob#^web-capture]]#",
                    depth: 1,
                    change: .removed
                ),
            ]
        )
        let preview = CaptureCommandSuccess(
            ok: true,
            dryRun: false,
            routed: false,
            routeLabel: "",
            relativeTarget: "2026/20260928.md",
            target: "/tmp/vault/2026/20260928.md",
            text: "=x",
            taskLine: "\t- [[bob#^web-capture]]#",
            kind: "pomodoro_close",
            created: "2026-09-28",
            placement: "closed"
        )

        XCTAssertFalse(
            CapturePomodoroBlockPresentation.covers(preview, blocks: [removedOnly])
        )
        XCTAssertTrue(
            CapturePomodoroBlockPresentation.covers(success, blocks: success.pomodoroBlocks)
        )
    }
}

private enum BlockPresentationFixtureError: Error {
    case expectedSuccess
}
